# Allow configuration in yaml files to be overridden by environment variable values
youTubeApiKey: KILLRVIDEO_YOUTUBE_API_KEY

cassandra:
  keyspace: KILLRVIDEO_CASSANDRA_KEYSPACE
  replication: KILLRVIDEO_CASSANDRA_REPLICATION

loggingLevel: KILLRVIDEO_LOGGING_LEVEL