# Key required for calling YouTube APIs
youTubeApiKey: REPLACE_WITH_YOUR_KEY

# Cassandra settings
cassandra:
  # The keyspace (will be created if it doesn't exist)
  keyspace: killrvideo_sample_data
  # The replication string (i.e. after WITH REPLICATION) to use when creating the keyspace if it doesn't exist
  replication: "{ 'class' : 'SimpleStrategy', 'replication_factor' : 1 }"
  # The username and password needed to authenticate to the cluster.  
  # Either set these values here directly or use the KILLRVIDEO_DSE_USERNAME and KILLRVIDEO_DSE_PASSWORD environment variables. 
  dseUsername: null
  dsePassword: null

# The minimum log level to output
loggingLevel: verbose

# Default schedules for running tasks, parsed by Later.js text parser
# (see http://bunkat.github.io/later/parsers.html#text for examples)
schedules:
  addSampleComment:
  - every 1 minute

  addSampleRating:
  - every 20 seconds

  addSampleUser:
  - every 30 minutes

  addSampleVideo:
  - every 8 hours

  addSampleVideoView:
  - every 1 seconds